name: Update Books Section

on:
  pull_request:
    paths:
      - 'books.json'
  workflow_dispatch:

jobs:
  update-books:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies (if any)
      - name: Install dependencies
        run: pip install jinja2

      # 4. Run the script
      - name: Update README books section
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          python .github/scripts/update_books.py

      # 5. Commit & push changes
      - name: Commit updated README
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update books section from PR" || echo "No changes to commit"
          git push
